matrix:
  include:
    # - language: objective-c
    #   osx_image: xcode9.4
    #   cache:
    #     timeout: 600
    #     directories:
    #       - $HOME/.cache/yarn
    #       - node_modules
    #   env:
    #     global:
    #     - LC_CTYPE=en_US.UTF-8
    #     - LANG=en_US.UTF-8

    #   before_install:
    #     - nvm install 9
    #     - which node
    #     - node --version
    #     - export TRAVIS_NODE_BINARY=$(which node)
    #     - sudo gem install xcpretty

    #   install:
    #     - npm install

    #   script:
    #     - set -o pipefail
    #     - npm run ci:check
    #     - npm run test:ios | xcpretty
    #     - npm run swiftlint
    - language: android
      android:
        components:
          - build-tools-26.0.2
          - android-26
          - android-23
          - sys-img-x86-android-23
          - tools
          - platform-tools
          - tools
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      before_install:
        - nvm install 9
        - which node
        - node --version
        - export TRAVIS_NODE_BINARY=$(which node)
        - android list targets
        - echo no | android create avd --force -n test -t android-23 --abi x86
        - emulator -avd test -no-audio -no-window &
      install:
        - npm install
        # Emulator Management: Create, Start and Wait
      before_script:
        - android-wait-for-emulator
        - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
        - adb shell input keyevent 82 &
      script:
        - npm run ktlint
        - npm run test:android

