name: CI

on:
  pull_request:
  push:
    branches: master

jobs:
  ci-check:
    runs-on: ubuntu-latest
    name: JavaScript tests
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v2
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn
    - run: yarn ci:check
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.3
  ios:
    runs-on: macos-10.15
    name: iOS tests
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1.2.1
      with:
        xcode-version: 12.2.0
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
    - uses: actions/cache@v2
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn
    - uses: actions/cache@v2
      with:
        path: ~/.cocoapods/repos
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
    - run: bundle install
    - run: cd native/iosTest && bundle exec pod install
    - run: yarn test:ios
    - run: yarn swiftlint
  android:
    # https://github.com/ReactiveCircus/android-emulator-runner/issues/46
    runs-on: macos-10.15
    name: Android tests
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v2
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        working-directory: ./native/androidTest
        script: ./gradlew connectedAndroidTest
    - run: yarn ktlint
  docs:
    runs-on: ubuntu-latest
    name: Check documentation
    steps:
    - uses: actions/checkout@v2
    - run: (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
    - run: (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
    - run: cargo install-update -a
    - run: ./scripts/mdbook

