name: CI

on:
  pull_request:
  push:
    branches: master

jobs:
  ci-check:
    runs-on: ubuntu-latest
    name: Check CI
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v2
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn
    - run: yarn ci:check
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.3
  ios:
    runs-on: macos-10.15
    name: Check iOS
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1.2.1
      with:
        xcode-version: 12.2.0
    - uses: actions/cache@v2
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - uses: actions/cache@v2
      with:
        path: native/iosTest/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
    - run: yarn
    - run: bundle install
    - run: cd native/iosTest && bundle exec pod install
    - run: yarn test:ios
    - run: yarn swiftlint
  android:
    # https://github.com/ReactiveCircus/android-emulator-runner/issues/46
    runs-on: macos-10.15
    if: ${{ false }}
    name: Check Android
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v2
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn
    - run: scripts/any-android-device
    - run: yarn test:android
    - run: yarn ktlint

